create extension if not exists pgcrypto;
create sequence if not exists public.participant_sessions_participant_number_seq;

create table if not exists public.participant_sessions (
  id uuid primary key default gen_random_uuid(),
  participant_number bigint not null default nextval('public.participant_sessions_participant_number_seq'),
  participant_id text not null unique,
  study_id text not null,
  consent_timestamp timestamptz,
  completed_at timestamptz,
  age_category text,
  province text,
  gender_identity text,
  online_shopping_frequency text,
  primary_shopping_device text,
  retailer_familiarity text,
  submission_source text not null default 'github-pages',
  participant_profile jsonb not null default '{}'::jsonb,
  device_info jsonb not null default '{}'::jsonb,
  page_summary jsonb not null default '[]'::jsonb,
  total_valid_samples integer not null default 0,
  total_invalid_samples integer not null default 0,
  session_payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.page_responses (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.participant_sessions(id) on delete cascade,
  participant_id text not null,
  participant_number bigint,
  study_id text not null,
  page_id text not null,
  page_title text,
  family_id text,
  family_label text,
  case_id text,
  case_title text,
  template text,
  image_set_id text,
  question text,
  selection text,
  selected_label text,
  stimulus_time_on_page_ms integer not null default 0,
  selection_popup_time_on_page_ms integer not null default 0,
  combined_time_on_page_ms integer not null default 0,
  stimulus_valid_sample_count integer not null default 0,
  stimulus_invalid_sample_count integer not null default 0,
  selection_popup_valid_sample_count integer not null default 0,
  selection_popup_invalid_sample_count integer not null default 0,
  combined_valid_sample_count integer not null default 0,
  combined_invalid_sample_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (session_id, page_id)
);

create table if not exists public.page_phase_metrics (
  id uuid primary key default gen_random_uuid(),
  page_response_id uuid not null references public.page_responses(id) on delete cascade,
  session_id uuid not null references public.participant_sessions(id) on delete cascade,
  participant_id text not null,
  participant_number bigint,
  study_id text not null,
  page_id text not null,
  phase text not null check (phase in ('stimulus', 'selectionPopup')),
  started_at timestamptz,
  ended_at timestamptz,
  time_on_page_ms integer not null default 0,
  valid_sample_count integer not null default 0,
  invalid_sample_count integer not null default 0,
  created_at timestamptz not null default now(),
  unique (page_response_id, phase)
);

create table if not exists public.gaze_samples (
  id bigint generated by default as identity primary key,
  page_response_id uuid not null references public.page_responses(id) on delete cascade,
  session_id uuid not null references public.participant_sessions(id) on delete cascade,
  participant_id text not null,
  participant_number bigint,
  study_id text not null,
  page_id text not null,
  phase text not null check (phase in ('stimulus', 'selectionPopup')),
  sample_index integer not null,
  sample_timestamp timestamptz,
  elapsed_time_ms integer,
  valid boolean not null default false,
  raw_x double precision,
  raw_y double precision,
  x double precision,
  y double precision,
  relative_x double precision,
  relative_y double precision,
  page_width double precision,
  page_height double precision,
  in_bounds boolean not null default false,
  created_at timestamptz not null default now(),
  unique (page_response_id, phase, sample_index)
);

alter sequence public.participant_sessions_participant_number_seq
  owned by public.participant_sessions.participant_number;

alter table public.participant_sessions
  add column if not exists participant_number bigint,
  add column if not exists age_category text,
  add column if not exists province text,
  add column if not exists gender_identity text,
  add column if not exists online_shopping_frequency text,
  add column if not exists primary_shopping_device text,
  add column if not exists retailer_familiarity text,
  add column if not exists participant_profile jsonb not null default '{}'::jsonb;

alter table public.participant_sessions
  alter column participant_number
  set default nextval('public.participant_sessions_participant_number_seq');

update public.participant_sessions
set participant_number = nextval('public.participant_sessions_participant_number_seq')
where participant_number is null;

alter table public.participant_sessions
  alter column participant_number set not null;

select setval(
  'public.participant_sessions_participant_number_seq',
  coalesce((select max(participant_number) from public.participant_sessions), 0) + 1,
  false
);

alter table public.participant_sessions enable row level security;
alter table public.page_responses enable row level security;
alter table public.page_phase_metrics enable row level security;
alter table public.gaze_samples enable row level security;

create index if not exists participant_sessions_study_id_idx
  on public.participant_sessions (study_id);

create index if not exists participant_sessions_province_idx
  on public.participant_sessions (province);

create index if not exists participant_sessions_age_category_idx
  on public.participant_sessions (age_category);

create unique index if not exists participant_sessions_participant_number_idx
  on public.participant_sessions (participant_number);

create index if not exists page_responses_session_id_idx
  on public.page_responses (session_id);

create index if not exists page_responses_page_id_idx
  on public.page_responses (page_id);

create index if not exists page_responses_case_id_idx
  on public.page_responses (case_id);

create index if not exists page_phase_metrics_page_response_id_idx
  on public.page_phase_metrics (page_response_id);

create index if not exists page_phase_metrics_phase_idx
  on public.page_phase_metrics (phase);

create index if not exists gaze_samples_page_response_id_idx
  on public.gaze_samples (page_response_id);

create index if not exists gaze_samples_page_phase_idx
  on public.gaze_samples (page_id, phase);

create index if not exists gaze_samples_valid_idx
  on public.gaze_samples (valid);

create or replace function public.normalize_participant_session(p_session_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.participant_sessions%rowtype;
  page_key text;
  page_value jsonb;
  page_response_id uuid;
  phase_name text;
  phase_value jsonb;
  sample_value jsonb;
  sample_index integer;
begin
  select *
  into session_row
  from public.participant_sessions
  where id = p_session_id;

  if not found then
    return;
  end if;

  delete from public.page_responses
  where session_id = session_row.id;

  for page_key, page_value in
    select key, value
    from jsonb_each(coalesce(session_row.session_payload->'pages', '{}'::jsonb))
  loop
    insert into public.page_responses (
      session_id,
      participant_id,
      participant_number,
      study_id,
      page_id,
      page_title,
      family_id,
      family_label,
      case_id,
      case_title,
      template,
      image_set_id,
      question,
      selection,
      selected_label,
      stimulus_time_on_page_ms,
      selection_popup_time_on_page_ms,
      combined_time_on_page_ms,
      stimulus_valid_sample_count,
      stimulus_invalid_sample_count,
      selection_popup_valid_sample_count,
      selection_popup_invalid_sample_count,
      combined_valid_sample_count,
      combined_invalid_sample_count
    )
    values (
      session_row.participant_id,
      session_row.participant_id,
      session_row.participant_number,
      session_row.study_id,
      page_key,
      page_value->>'pageTitle',
      page_value->>'familyId',
      page_value->>'familyLabel',
      page_value->>'caseId',
      page_value->>'caseTitle',
      page_value->>'template',
      page_value->>'imageSetId',
      page_value->>'question',
      page_value->>'selection',
      page_value->>'selectedLabel',
      coalesce((page_value->>'timeOnPageMs')::integer, 0),
      coalesce((page_value->>'selectionPopupTimeOnPageMs')::integer, 0),
      coalesce((page_value->>'timeOnPageMs')::integer, 0) +
        coalesce((page_value->>'selectionPopupTimeOnPageMs')::integer, 0),
      coalesce((page_value->>'validSampleCount')::integer, 0),
      coalesce((page_value->>'invalidSampleCount')::integer, 0),
      coalesce((page_value->>'selectionPopupValidSampleCount')::integer, 0),
      coalesce((page_value->>'selectionPopupInvalidSampleCount')::integer, 0),
      coalesce((page_value->>'validSampleCount')::integer, 0) +
        coalesce((page_value->>'selectionPopupValidSampleCount')::integer, 0),
      coalesce((page_value->>'invalidSampleCount')::integer, 0) +
        coalesce((page_value->>'selectionPopupInvalidSampleCount')::integer, 0)
    )
    returning id
    into page_response_id;

    foreach phase_name in array array['stimulus', 'selectionPopup']
    loop
      phase_value := coalesce(page_value->'phases'->phase_name, '{}'::jsonb);

      insert into public.page_phase_metrics (
        page_response_id,
        session_id,
        participant_id,
        participant_number,
        study_id,
        page_id,
        phase,
        started_at,
        ended_at,
        time_on_page_ms,
        valid_sample_count,
        invalid_sample_count
      )
      values (
        page_response_id,
        session_row.id,
        session_row.participant_id,
        session_row.participant_number,
        session_row.study_id,
        page_key,
        phase_name,
        nullif(phase_value->>'startedAt', '')::timestamptz,
        nullif(phase_value->>'endedAt', '')::timestamptz,
        coalesce((phase_value->>'timeOnPageMs')::integer, 0),
        coalesce((phase_value->>'validSampleCount')::integer, 0),
        coalesce((phase_value->>'invalidSampleCount')::integer, 0)
      );

      sample_index := 0;
      for sample_value in
        select value
        from jsonb_array_elements(coalesce(phase_value->'gazePoints', '[]'::jsonb))
      loop
        insert into public.gaze_samples (
          page_response_id,
          session_id,
          participant_id,
          participant_number,
          study_id,
          page_id,
          phase,
          sample_index,
          sample_timestamp,
          elapsed_time_ms,
          valid,
          raw_x,
          raw_y,
          x,
          y,
          relative_x,
          relative_y,
          page_width,
          page_height,
          in_bounds
        )
        values (
          page_response_id,
          session_row.id,
          session_row.participant_id,
          session_row.participant_number,
          session_row.study_id,
          page_key,
          phase_name,
          sample_index,
          nullif(sample_value->>'timestamp', '')::timestamptz,
          nullif(sample_value->>'elapsedTimeMs', '')::integer,
          coalesce((sample_value->>'valid')::boolean, false),
          nullif(sample_value->>'rawX', '')::double precision,
          nullif(sample_value->>'rawY', '')::double precision,
          nullif(sample_value->>'x', '')::double precision,
          nullif(sample_value->>'y', '')::double precision,
          nullif(sample_value->>'relativeX', '')::double precision,
          nullif(sample_value->>'relativeY', '')::double precision,
          nullif(sample_value->>'pageWidth', '')::double precision,
          nullif(sample_value->>'pageHeight', '')::double precision,
          coalesce((sample_value->>'inBounds')::boolean, false)
        );
        sample_index := sample_index + 1;
      end loop;
    end loop;
  end loop;
end;
$$;

create or replace function public.rebuild_normalized_participant_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  session_entry record;
begin
  truncate table public.gaze_samples restart identity cascade;
  truncate table public.page_phase_metrics cascade;
  truncate table public.page_responses cascade;

  for session_entry in
    select id from public.participant_sessions
  loop
    perform public.normalize_participant_session(session_entry.id);
  end loop;
end;
$$;

create or replace view public.page_response_analysis as
select
  pr.id as page_response_id,
  pr.session_id,
  ps.participant_id,
  ps.participant_number,
  ps.study_id,
  ps.age_category,
  ps.province,
  ps.gender_identity,
  ps.online_shopping_frequency,
  ps.primary_shopping_device,
  ps.retailer_familiarity,
  pr.page_id,
  pr.page_title,
  pr.family_id,
  pr.family_label,
  pr.case_id,
  pr.case_title,
  pr.template,
  pr.image_set_id,
  pr.question,
  pr.selection,
  pr.selected_label,
  pr.stimulus_time_on_page_ms,
  pr.selection_popup_time_on_page_ms,
  pr.combined_time_on_page_ms,
  pr.stimulus_valid_sample_count,
  pr.stimulus_invalid_sample_count,
  pr.selection_popup_valid_sample_count,
  pr.selection_popup_invalid_sample_count,
  pr.combined_valid_sample_count,
  pr.combined_invalid_sample_count,
  ps.created_at as session_created_at
from public.page_responses pr
join public.participant_sessions ps
  on ps.id = pr.session_id;

create or replace view public.gaze_sample_analysis as
select
  gs.id as gaze_sample_id,
  gs.page_response_id,
  gs.session_id,
  gs.participant_id,
  gs.participant_number,
  gs.study_id,
  ps.age_category,
  ps.province,
  ps.gender_identity,
  ps.online_shopping_frequency,
  ps.primary_shopping_device,
  ps.retailer_familiarity,
  pr.page_id,
  pr.page_title,
  pr.family_id,
  pr.family_label,
  pr.case_id,
  pr.case_title,
  pr.template,
  pr.image_set_id,
  gs.phase,
  gs.sample_index,
  gs.sample_timestamp,
  gs.elapsed_time_ms,
  gs.valid,
  gs.raw_x,
  gs.raw_y,
  gs.x,
  gs.y,
  gs.relative_x,
  gs.relative_y,
  gs.page_width,
  gs.page_height,
  gs.in_bounds
from public.gaze_samples gs
join public.page_responses pr
  on pr.id = gs.page_response_id
join public.participant_sessions ps
  on ps.id = gs.session_id;

create or replace function public.submit_participant_session(payload jsonb)
returns table (participant_number bigint, duplicate boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_number bigint;
  inserted_id uuid;
begin
  insert into public.participant_sessions (
    participant_id,
    study_id,
    consent_timestamp,
    completed_at,
    age_category,
    province,
    gender_identity,
    online_shopping_frequency,
    primary_shopping_device,
    retailer_familiarity,
    submission_source,
    participant_profile,
    device_info,
    page_summary,
    total_valid_samples,
    total_invalid_samples,
    session_payload
  )
  values (
    payload->>'participant_id',
    payload->>'study_id',
    nullif(payload->>'consent_timestamp', '')::timestamptz,
    nullif(payload->>'completed_at', '')::timestamptz,
    nullif(payload->>'age_category', ''),
    nullif(payload->>'province', ''),
    nullif(payload->>'gender_identity', ''),
    nullif(payload->>'online_shopping_frequency', ''),
    nullif(payload->>'primary_shopping_device', ''),
    nullif(payload->>'retailer_familiarity', ''),
    coalesce(nullif(payload->>'submission_source', ''), 'github-pages'),
    coalesce(payload->'participant_profile', '{}'::jsonb),
    coalesce(payload->'device_info', '{}'::jsonb),
    coalesce(payload->'page_summary', '[]'::jsonb),
    coalesce((payload->>'total_valid_samples')::integer, 0),
    coalesce((payload->>'total_invalid_samples')::integer, 0),
    coalesce(payload->'session_payload', '{}'::jsonb)
  )
  on conflict (participant_id) do nothing
  returning public.participant_sessions.id, public.participant_sessions.participant_number
  into inserted_id, inserted_number;

  if inserted_number is not null then
    perform public.normalize_participant_session(inserted_id);
    return query select inserted_number, false;
    return;
  end if;

  select participant_sessions.id, participant_sessions.participant_number
  into inserted_id, inserted_number
  from public.participant_sessions
  where participant_sessions.participant_id = payload->>'participant_id';

  if inserted_id is not null and not exists (
    select 1 from public.page_responses where session_id = inserted_id
  ) then
    perform public.normalize_participant_session(inserted_id);
  end if;

  return query select inserted_number, true;
end;
$$;

grant execute on function public.submit_participant_session(jsonb) to anon;
grant usage, select on sequence public.participant_sessions_participant_number_seq to anon;

drop policy if exists "Allow anonymous participant inserts" on public.participant_sessions;
create policy "Allow anonymous participant inserts"
on public.participant_sessions
for insert
to anon
with check (true);
